---
- debug:
    msg: "Campsites: {{ campsites }}. Number of nights: {{ number_of_nights }}."

- name: Get available stuff
  uri:
    url: 'https://bccrdr.usedirect.com/rdr/rdr/search/place'
    method: POST
    headers: 
      Content-Type: "application/json;charset=utf-8"
    status_code: 200
    validate_certs: no
    body: "{{ lookup('template','templates/body.json.j2') | to_nice_json }}"
    body_format: json
  register: response
  delegate_to: localhost

- name: debugging
  debug:
    msg: "Response: {{ response }}"

# - name: loop debug
#   debug:
#     msg: item.value.UnitTypes {{ item.value.UnitTypes }}
#   when: item.value.Available is true
#   with_items: "{{ response.json.SelectedPlace.Facilities | dict2items }}"

- name: set some facts
  block:
    - name: "set facts"
      set_fact:
        twilio_message: "{{ lookup('template', 'templates/message.j2') }}"
      when: item.value.Available == true
      with_items: "{{ response.json.SelectedPlace.Facilities | dict2items }}"
  when: response.json.SelectedPlace.Facilities is defined

- name: twilio message
  debug:
    msg: "{{ twilio_message }}"
  when: twilio_message is defined

- name: Send twilio message
  twilio:
    msg: "{{ twilio_message }}"
    account_sid: "{{ twilio_account_sid }}"
    auth_token: "{{ twilio_auth_token }}"
    from_number: "{{ twilio_from_number }}"
    to_number: "{{ twilio_to_number }}"
  delegate_to: localhost
  when: twilio_message is defined

# - name: Get current job template schedule
#   uri:
#     url: "{{ awx_url }}/api/v2/job_templates/{{ awx_job_template_id}}/schedules/"
#     method: GET
#     user: colincalnan
#     password: XDtyPnLf2Z
#     force_basic_auth: yes
#     headers: 
#       Content-Type: "application/json"
#     status_code: 200
#     validate_certs: no
#   register: schedule
#   when: twilio_message is defined

# - name: Deactivate the job template when a message is sent
#   uri:
#     url: "{{ awx_url }}/api/v2/schedules/{{ schedule.json.results[0].id }}/"
#     method: PATCH
#     headers: 
#       Content-Type: "application/json"
#     status_code: 200
#     user: "{{ awx_username }}"
#     password: "{{ awx_password }}"
#     force_basic_auth: yes
#     validate_certs: no
#     body:
#       enabled: false
#     body_format: json
#   register: deactivate
#   when: twilio_message is defined
