---

- name: Loop block
  include_tasks: request-notify.yml
  loop: "{{ campsites }}"
  loop_control:
    loop_var: campsite

# {% if js['SelectedPlace']['Available']:
#     for facility_index in js['SelectedPlace']['Facilities']:
#         facility = js['SelectedPlace']['Facilities'][facility_index]
#         if facility['Available']:
#             for unit_type_index in facility['UnitTypes']:
#                 unit_type = facility['UnitTypes'][unit_type_index]
#                 if unit_type['Available'] and not  unit_type['AvailableFiltered'] and unit_type['AvailableCount'] > 0:
#                     print(f"{unit_type['AvailableCount']:d} '{unit_type['Name']}' spots ({facility['Name']}) available at '{js['SelectedPlace']['Name']}'")
